name: Services for Graph RAG

services:
  redis:
    image: redis:alpine
    container_name: redis_app
    # ports:
    #   - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - backend_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 384M
        reservations:
          memory: 128M
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: attijary-front-app
    container_name: frontend_app
    restart: unless-stopped
    ports:
      - "4200:8080"
    env_file:
      - ./frontend/.env
    networks:
      - frontend_network
    
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend_app:v1.0
    container_name: backend_app
    restart: unless-stopped
    ports:
      - "3000:5000"
    env_file:
      - ./backend/.env
    networks:
      - backend_network
      - frontend_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1250M
        reservations:
          memory: 512M

  celery_worker:
    image: backend_app:v1.0
    restart: unless-stopped
    container_name: celery_worker_app
    # Overrides the default CMD in your Dockerfile
    command: celery -A celery_worker.celery_app worker --loglevel=info --pool=threads
    networks:
      - backend_network
    env_file:
      - ./backend/.env
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1500M
        reservations:
          memory: 512M



volumes:
  redis_data:
networks:
  backend_network:
  frontend_network:
