"""Added index in the chat table called idx_user_id_created_at

Revision ID: 7ce7be1c96a8
Revises: d3fb95dd871b
Create Date: 2026-09-15 15:33:46.745435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce7be1c96a8'
down_revision = 'd3fb95dd871b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.create_index('idx_user_id_created_at', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_index('idx_user_id_created_at')

    # ### end Alembic commands ###
