"""Added default date

Revision ID: 7d69c28222fe
Revises: 8e9c0b62d123
Create Date: 2026-08-07 14:39:40.431734

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7d69c28222fe"
down_revision = "8e9c0b62d123"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.alter_column(
            "date",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.alter_column(
            "date",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            server_default=None,
            existing_nullable=False,
        )

    # ### end Alembic commands ###
