# name: CD - Backend

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'backend/**'

# concurrency:
#   group: cd-backend-production
#   cancel-in-progress: true

# jobs:
#     # cd-backend:
