# name: CD - Frontend

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'frontend/**'

# concurrency:
#   group: cd-frontend-production
#   cancel-in-progress: true

# jobs:
#     # cd-frontend:
