# Run on every pull request targeting main when files in backend change
on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Run secret scanning
  secret-scanning:
    uses: ./.github/workflows/reusable-secret-scanning.yml
    secrets:
      GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Run dependency scanning
  dependency-scanning:
    uses: ./.github/workflows/reusable-dependency-scanning.yml

  # Run Security test
  codeql-analysis:
    uses: ./.github/workflows/reusable-codeQl-scanning.yml
    with:
      languages: 'python'