on: [workflow_call]

jobs:
    dependency-scanning:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Dependency Review
            uses: actions/dependency-review-action@v4
            with:
                # Optional configurations:
                fail-on-severity: 'high' # Choices: low, moderate, high, critical
                allow-licenses: 'MIT, Apache-2.0' # Fail if a package uses an unapproved license
                base-ref: ${{ github.event.pull_request.base.sha || github.event.before }}
                head-ref: ${{ github.event.pull_request.head.sha || github.event.after }}
