on:
    workflow_call:
        secrets:
            GITGUARDIAN_API_KEY:
                required: true
                description: 'GitGuardian API key for secret scanning'
            GITHUB_TOKEN:
                required: true
                description: 'GitHub token for authentication'

jobs:
    # Run GitGuarding scanning
    gitguardian-scanning:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0 # Fetch all history for all branches and tags
            - name: GitGuardian Scan
              uses: GitGuardian/ggshield-action@v1.23.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
